trigger:
  - demo


pool:
  vmImage: windows-latest


steps:
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean test'


  
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |


        Invoke-WebRequest -Uri 'https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.23.0/allure-commandline-2.23.0.zip' -OutFile 'allure.zip'


        Expand-Archive -Path 'allure.zip' -DestinationPath '$(Agent.ToolsDirectory)'


        Set-Variable -Name 'AllureCommand' -Value "$(Agent.ToolsDirectory)/allure-2.23.0/bin/allure.bat" -Scope Script -Force


        $(Agent.ToolsDirectory)/allure-2.23.0/bin/allure.bat generate allure-results -o allure-report --clean
    displayName: 'Generate Allure Report'


  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(System.DefaultWorkingDirectory)\allure-report
      artifactName: 'Allure Reports'


  - task: PublishAllureReport@1
    inputs:
      tabName: 'Published-Allure-Report'
      reportDir: 'allure-report'








